name: spark_example
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - pip:
    - mlflow>=1.0
    - pyspark
    - findspark
    - sklearn
    - numpy
    - python-dateutil

